### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by ThellraAK** [towalink/wgconfig#1]
I'm unfamiliar with the license you chose.

If I used this project, I understand I would need to attribute you that I'm using it, and make the source available upon request.

What I don't understand is, would I need to use the same license for the larger project, which uses your program, or would I be able to use your program, and license my program which uses your program anyway I want, as long as I.

Attribute you/this project, as well as make the source available

The formatting on this question is all wrong, if you don't understand what I'm asking, please let me know.

**Comment by towalink** [comment]
Glad you find this project useful. This library got created for use as part of a bigger WireGuard-based connectivity solution which will be released under AGPL license soon. Since I assumed the "wgconfig" library would be useful to others, too, I released it already. Without much thinking, I chose the same license as the "parent project".

The AGPL is a variation of the GPL. Many widely-used OpenSource licenses tend to be compatible (lawyers see nuances). This means you don't need to use the same license but can also use compatible ones in your projects like the GPL.
If the current license (AGPL) of the "wgconfig" library is an issue to people, I'll consider changing to LGPL which is less restrictive.
