### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by thawri1** [towalink/wgconfig#2]
I try to use this in Django project but i encounter this error:
`[Errno 13] Permission denied: '/etc/wireguard/wg0.conf'`

how can i fix it?
thank you.

**Comment by towalink** [comment]
The user running your application needs to have the required permissions to access the files in the /etc/wireguard folder.

One requires root permissions to change the files in /etc/wireguard (unless something else is configured explicitly). This makes sense since the files contain sensitive data like private keys. Thus the wgconfig library needs to be executed with the required permissions (usually root) to change these files.
Your application is probably running as a non-root user (in the Django case maybe your web server user). Thus you get a "permission denied" error.

**Comment by thawri1** [comment]
thanks for your reply
